import { readFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { validateEvent, validateEventsArray } from '../src/lib/schema.ts';
import { normalizeIncomingEvent } from './lib/normalize-incoming-event.mjs';
import { loadPlayers, savePlayers } from './lib/players.mjs';
import { loadDecks, saveDecks } from './lib/decks.mjs';
import { EVENTS_DIR, assertNotImportedTwice, EVENT_ID_PATTERN, eventFileName, eventIdFor, loadEventFiles, sortEvents, writeEventFile } from './lib/event-store.mjs';

const root = process.cwd();

function parseArg(flag) {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return null;
  return process.argv[idx + 1] ?? null;
}

function parseBoolean(flag) {
  return process.argv.includes(flag);
}

function logNewDecks(newDecks, title) {
  if (newDecks.length === 0) return;
  console.log(`${title}: ${newDecks.map((deck) => `${deck.id} (${deck.name}, ${deck.colors})`).join(', ')}`);
}

function logNewPlayers(newPlayers, title) {
  if (newPlayers.length === 0) return;
  console.log(`${title}: ${newPlayers.map((player) => `${player.id} (${player.name})`).join(', ')}`);
}

async function main() {
  const fileArg = parseArg('--file');
  const dryRun = parseBoolean('--dry-run');
  const deleteSource = parseBoolean('--delete-source');
  const allowSameDay = parseBoolean('--allow-same-day');

  if (!fileArg) {
    throw new Error('Usage: node scripts/add-event.mjs --file <path-to-event.json> [--dry-run] [--delete-source] [--allow-same-day]');
  }

  const incomingPath = path.resolve(root, fileArg);
  const incomingRaw = await readFile(incomingPath, 'utf8');
  const incomingEvent = JSON.parse(incomingRaw);

  const entries = await loadEventFiles(root);
  const currentEvents = entries.map((entry) => entry.event);
  validateEventsArray(currentEvents);

  const players = await loadPlayers(root);
  const decks = await loadDecks(root);
  const { event: normalizedIncomingEvent, newPlayers, newDecks } = normalizeIncomingEvent(incomingEvent, players, decks);
  const explicitId = typeof normalizedIncomingEvent.id === 'string' ? normalizedIncomingEvent.id.trim() : '';
  if (explicitId && !EVENT_ID_PATTERN.test(explicitId)) {
    throw new Error(`Invalid event id "${explicitId}". Omit it or use <date>-<place>-<type>, e.g. 2026-09-21-sidequest-weekly.`);
  }
  normalizedIncomingEvent.id = explicitId || eventIdFor(normalizedIncomingEvent, currentEvents.map((event) => event.id));
  validateEvent(normalizedIncomingEvent, 'incomingEvent');

  const duplicate = currentEvents.find((event) => event.id === normalizedIncomingEvent.id);
  if (duplicate) {
    throw new Error(`Event with id "${normalizedIncomingEvent.id}" already exists in ${EVENTS_DIR}.`);
  }
  assertNotImportedTwice(currentEvents, normalizedIncomingEvent, allowSameDay);

  validateEventsArray(sortEvents([...currentEvents, normalizedIncomingEvent]));
  const file = eventFileName(normalizedIncomingEvent);

  if (dryRun) {
    console.log(`Dry run OK. Event ${normalizedIncomingEvent.id} can be added as ${EVENTS_DIR}/${file}.`);
    logNewPlayers(newPlayers, 'Would add new players');
    logNewDecks(newDecks, 'Would add new decks');
    return;
  }

  const written = await writeEventFile(root, file, normalizedIncomingEvent);
  console.log(`Added event ${normalizedIncomingEvent.id} -> ${written}`);
  if (newPlayers.length > 0) {
    await savePlayers(root, [...players, ...newPlayers]);
    logNewPlayers(newPlayers, 'Added new players to data/players.json');
  }
  if (newDecks.length > 0) {
    await saveDecks(root, [...decks, ...newDecks]);
    logNewDecks(newDecks, 'Added new decks to data/decks.json');
  }

  if (deleteSource) {
    await unlink(incomingPath);
    console.log(`Deleted source file ${fileArg}`);
  }

  console.log('Next step: commit the event file (and data/players.json / data/decks.json when they changed). Site data is regenerated by npm run generate-data.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
