import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { validateEvent, validateEventsArray } from '../src/lib/schema.ts';
import { applyEventDefaults, normalizeIncomingEvent } from './lib/normalize-incoming-event.mjs';
import { EVENTS_DIR, loadEventFiles, sortEvents, writeEventFile } from './lib/event-store.mjs';
import { loadPlayers, savePlayers } from './lib/players.mjs';
import { loadDecks, saveDecks } from './lib/decks.mjs';

// Re-normalizes an edited event file in place: resolves players, recalculates
// standings totals from rounds and validates the result.

const root = process.cwd();

function parseArg(flag) {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return null;
  return process.argv[idx + 1] ?? null;
}

async function main() {
  const fileArg = parseArg('--file');
  const dryRun = process.argv.includes('--dry-run');

  if (!fileArg) {
    throw new Error(`Usage: node scripts/update-event.mjs --file ${EVENTS_DIR}/<event-file>.json [--dry-run]`);
  }

  const filePath = path.resolve(root, fileArg);
  const eventsDir = path.resolve(root, EVENTS_DIR);
  if (path.dirname(filePath) !== eventsDir) {
    throw new Error(`Event file must be in ${EVENTS_DIR}: ${fileArg}`);
  }
  const file = path.basename(filePath);

  const edited = applyEventDefaults(JSON.parse(await readFile(filePath, 'utf8')));
  const entries = await loadEventFiles(root);
  const players = await loadPlayers(root);

  const decks = await loadDecks(root);
  const { event: normalized, newPlayers, newDecks } = normalizeIncomingEvent(edited, players, decks);
  validateEvent(normalized, file);

  const others = entries.filter((entry) => entry.file !== file).map((entry) => entry.event);
  validateEventsArray(sortEvents([...others, normalized]));

  if (dryRun) {
    console.log(`Dry run OK. ${EVENTS_DIR}/${file} is valid.`);
    if (newPlayers.length > 0) {
      console.log(`Would add new players: ${newPlayers.map((p) => `${p.id} (${p.name})`).join(', ')}`);
    }
    if (newDecks.length > 0) {
      console.log(`Would add new decks: ${newDecks.map((d) => `${d.id} (${d.name}, ${d.colors})`).join(', ')}`);
    }
    return;
  }

  const written = await writeEventFile(root, file, normalized);
  console.log(`Updated ${written}`);
  if (newPlayers.length > 0) {
    await savePlayers(root, [...players, ...newPlayers]);
    console.log(`Added new players to data/players.json: ${newPlayers.map((p) => `${p.id} (${p.name})`).join(', ')}`);
  }
  if (newDecks.length > 0) {
    await saveDecks(root, [...decks, ...newDecks]);
    console.log(`Added new decks to data/decks.json: ${newDecks.map((d) => `${d.id} (${d.name}, ${d.colors})`).join(', ')}`);
  }
  console.log('Next step: commit the event file (and data/players.json / data/decks.json when they changed). Site data is regenerated by npm run generate-data.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
