import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { validateEvent, validateEventsArray } from './lib/events-validation.mjs';
import { applyEventDefaults, normalizeIncomingEvent } from './lib/normalize-incoming-event.mjs';
import { EVENTS_DIR, loadEventFiles, sortEvents, writeEventFile } from './lib/event-store.mjs';

// Re-normalizes an edited event file in place: resolves players, recalculates
// standings totals from rounds and validates the result.

const root = process.cwd();

function parseArg(flag) {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return null;
  return process.argv[idx + 1] ?? null;
}

async function main() {
  const fileArg = parseArg('--file');
  const dryRun = process.argv.includes('--dry-run');

  if (!fileArg) {
    throw new Error(`Usage: node scripts/update-event.mjs --file ${EVENTS_DIR}/<event-file>.json [--dry-run]`);
  }

  const filePath = path.resolve(root, fileArg);
  const eventsDir = path.resolve(root, EVENTS_DIR);
  if (path.dirname(filePath) !== eventsDir) {
    throw new Error(`Event file must be in ${EVENTS_DIR}: ${fileArg}`);
  }
  const file = path.basename(filePath);

  const edited = applyEventDefaults(JSON.parse(await readFile(filePath, 'utf8')));
  const entries = await loadEventFiles(root);
  const currentEvents = entries.map((entry) => entry.event);

  const normalized = normalizeIncomingEvent(edited, currentEvents);
  validateEvent(normalized, file);

  const others = entries.filter((entry) => entry.file !== file).map((entry) => entry.event);
  validateEventsArray(sortEvents([...others, normalized]));

  if (dryRun) {
    console.log(`Dry run OK. ${EVENTS_DIR}/${file} is valid.`);
    return;
  }

  const written = await writeEventFile(root, file, normalized);
  console.log(`Updated ${written}`);
  console.log('Next step: commit the event file. Site data is regenerated by npm run generate-data.');
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
